name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # 新增：設置 Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.18'
        cache: 'npm'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # 新增：Docker 層級緩存
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Login to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        project_id: '${{ secrets.GCP_PROJECT_ID }}'

    - name: Configure Docker for GCP
      run: gcloud auth configure-docker

    - name: Build and Push Container
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: gcr.io/${{ secrets.GCP_PROJECT_ID }}/next-line-app:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          NEXT_PUBLIC_LIFF_ID=${{ secrets.NEXT_PUBLIC_LIFF_ID }}
          NODE_ENV=production

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: next-line-app
        image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/next-line-app:${{ github.sha }}
        region: asia-east1
        flags: '--allow-unauthenticated'